nuget/Caliburn.Micro.nuspec

Adds two entries to the NuGet package definition to create packages for iOS and Android

Create NuGet packages for Xamarin Android and iOS

---

src/Caliburn.Micro/SimpleContainer.cs

Use only public constructors in SimpleContainer

---

src/Caliburn.Micro/EventAggregator.cs

Fixes issue #203 (NRE in EventAggregator)

---

src/Caliburn.Micro/ConductorBase.cs
src/Caliburn.Micro/ConductorWithCollectionAllActive.cs
src/Caliburn.Micro/ConductorWithCollectionOneActive.cs

Added missing documentation for parameter in EnsureItem methods.

---

src/Caliburn.Micro/ConductorBase.cs
src/Caliburn.Micro/PropertyChangedBase.cs
src/Caliburn.Micro/Screen.cs

This pullrequest partially resolves #279 (changing other event candidates as seperate pull request so you can decide on wether you want those changes or not)

virtual keyword for event

---

src/Caliburn.Micro.Platform/MessageBinder.cs
src/Caliburn.Micro.Tests.NET45/Caliburn.Micro.Tests.NET45.csproj
src/Caliburn.Micro.Tests.NET45/MessageBinderTests.cs

Case insensitive parameter recognition in MessageBinder

---

src/Caliburn.Micro/ConductorWithCollectionAllActive.cs

Typo in documentation of ConductorWithCollectionAllActive.cs

---

samples/features/Features.CrossPlatform.Shared/ViewModels/MenuViewModel.cs

Fix typo in MenuViewModel.cs

---

samples/features/Features.CrossPlatform.Shared/ViewModels/TabViewModel.cs

Fix typo in word "Deactivated"

Fix typo in TabViewModel.cs

---

samples/setup/Setup.Android/readme.md
samples/setup/Setup.iOS/readme.md

- iOS and Android setup projects had some swapped readme text (iOS talking about activities, Android talking about storyboards)

Sample Documentation Cleanup (iOS / Android mixup)

---

azure-pipeline.yml
src/Caliburn.Micro.Core/Caliburn.Micro.Core.csproj
src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj

It looks like https://github.com/onovotny/MSBuildSdkExtras/issues/173 and https://github.com/onovotny/MSBuildSdkExtras/issues/174 have been resolved in newer MSBuildSdkExtras version.

Remove MSBuildSdkExtras workarounds

---

src/Caliburn.Micro.Platform/BindingScope.cs

BindingScope.cs null exception occurred bug #716

BindingScope.cs null exception occurred

---

src/Caliburn.Micro.Core/EventAggregator.cs

Fixes #756
Just pass the cancellationtoken instead of CancellationToken.None. That must be how this was supposed to work.

Passed the cancellationtoken input instead of CancellationToken.None

---

src/Caliburn.Micro.Platform.Core/AssemblySource.cs
src/Caliburn.Micro.Platform.Tests/AssemblyCacheTests.cs

Check for multiple assemblies being added to the cache

---

samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.App.sln
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/App.xaml
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/App.xaml.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/AssemblyInfo.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Bootstrapper.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Caliburn.Micro.Tutorial.Wpf.csproj
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/DebugLogger.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Models/AboutModel.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Models/CategoryModel.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/ViewModels/AboutViewModel.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/ViewModels/CategoryViewModel.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/ViewModels/ShellViewModel.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Views/AboutView.xaml
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Views/AboutView.xaml.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Views/CategoryView.xaml
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Views/CategoryView.xaml.cs
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Views/ShellView.xaml
samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Views/ShellView.xaml.cs
samples/tutorals/WPF/Wpf.Tutorial/readme.md

Updated the readme.md file for the samples folder to reflect the presence of the tutorial
Note the tutorial has a readme.md file referring to the tutorial text.

Added the source code for the Wpf Tutorial.

---

src/Caliburn.Micro.Platform.Core/Caliburn.Micro.Platform.Core.csproj
src/Caliburn.Micro.Platform/ActionMessage.cs
src/Directory.Build.targets

Fix bindings that are not working with net6.0

---

samples/setup/Setup.Avalonia/App.axaml
samples/setup/Setup.Avalonia/Setup.Avalonia.csproj
src/Caliburn.Micro.Avalonia/Caliburn.Micro.Avalonia.csproj
src/Caliburn.Micro.Avalonia/Platforms/netcore-avalonia/AttachedCollection.cs
src/Caliburn.Micro.Avalonia/Platforms/netcore-avalonia/Parameter.cs
src/Caliburn.Micro.Avalonia/Platforms/netcore-avalonia/WindowManager.cs
src/Caliburn.Micro.Platform/Action.cs
src/Caliburn.Micro.Platform/ActionExecutionContext.cs
src/Caliburn.Micro.Platform/ActionMessage.cs
src/Caliburn.Micro.Platform/Bind.cs
src/Caliburn.Micro.Platform/BindingScope.cs
src/Caliburn.Micro.Platform/ChildResolver.cs
src/Caliburn.Micro.Platform/Message.cs
src/Caliburn.Micro.Platform/Parser.cs
src/Caliburn.Micro.Platform/View.cs
src/Caliburn.Micro.Platform/ViewLocator.cs
src/Caliburn.Micro.Platform/ViewModelBinder.cs

For reference: https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes

Update to Avalonia 11.0.0-preview5.

---

src/Caliburn.Micro.Avalonia/Caliburn.Micro.Avalonia.csproj
src/Caliburn.Micro.Platform/XamlPlatformProvider.cs
src/NuGet.config

Updates to new dispatcher api coming in the next preview (in a week or so).
Implements  GetViewCloseAction properly as dialog result has a different api to wpf.

Some more Avalonia fixes

---

samples/setup/Setup.Android/Resources/Resource.Designer.cs
samples/setup/Setup.Forms5/Setup.Forms5/Setup.Forms5.Android/Resources/Resource.designer.cs
samples/setup/Setup.Maui/App.xaml.cs
samples/setup/Setup.Maui/MauiProgram.cs
samples/setup/Setup.Maui/Services/IService.cs
samples/setup/Setup.Maui/Services/MyService.cs
samples/setup/Setup.Maui/Setup.Maui.csproj
src/Caliburn.Micro.Platform/Platforms/Maui/Android/CaliburnApplication.cs
src/Caliburn.Micro.Platform/Platforms/Maui/FormsApplication.cs
src/Caliburn.Micro.Platform/Platforms/Maui/Windows/CaliburnApplication.cs
src/Caliburn.Micro.Platform/Platforms/Maui/iOS/CaliburnApplicationDelegate.cs
src/global.json

Update the maui implementation to do dependency injection in Caliburn Micro MauiApplication instead of platform specific CaliburnApplication
Related to #831

Maui dependency injection

---

samples/features/Features.Avalonia/Features.Avalonia.csproj
samples/features/Features.Avalonia/Views/MenuView.axaml
samples/setup/Setup.Avalonia/Setup.Avalonia.csproj
src/Caliburn.Micro.Avalonia/Caliburn.Micro.Avalonia.csproj
src/Caliburn.Micro.Platform/ViewLocator.cs

simply updates to preview 7 release,
and fix critical issue where xaml parsing will explode.

Update Avalonia to Preview 7

---

src/Caliburn.Micro.Platform/Platforms/netcore-avalonia/WindowConductor.cs

This fixes https://github.com/AvaloniaUI/Avalonia/issues/12439

Run CanCloseAsync with DispatcherPriority Input.

---

src/Caliburn.Micro.Core.Tests/ConductorWithCollectionOneActiveTests.cs
src/Caliburn.Micro.Core/ConductorBaseWithActiveItem.cs

This fixed bug #906 for the next V4 release.
@vb2ae Please publish V4.0.213 NuGet release, thanks.

Include bug #906 fix to V4

---

src/Caliburn.Micro.Core/Caliburn.Micro.Core.csproj
src/Caliburn.Micro.Core/Readme.md
src/Caliburn.Micro.Maui.Tests/coverage.json
src/Caliburn.Micro.Maui/Caliburn.Micro.Maui.csproj
src/Caliburn.Micro.Maui/Readme.md
src/Caliburn.Micro.Platform.Core/Caliburn.Micro.Platform.Core.csproj
src/Caliburn.Micro.Platform.Core/Readme.md
src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj
src/Caliburn.Micro.Platform/Platforms/Maui/Windows/CaliburnApplication.cs
src/Caliburn.Micro.Platform/Readme.md
src/Caliburn.Micro.Xamarin.Forms/Caliburn.Micro.Xamarin.Forms.csproj
src/Caliburn.Micro.Xamarin.Forms/Readme.md

This pull request includes updates to multiple project files to add metadata for packaging, such as titles and package icons. The changes ensure that each project has a consistent title and icon for NuGet packaging.
* [`src/Caliburn.Micro.Core/Caliburn.Micro.Core.csproj`](diffhunk://#diff-5555b79aaee8a14d94af70b8465705692bc6456437c5097564e346d677ad3376R11-R12): Added `<Title>` and `<PackageIcon>` properties, and included the `CaliburnIcon.png` file in the package. [[1]](diffhunk://#diff-5555b79aaee8a14d94af70b8465705692bc6456437c5097564e346d677ad3376R11-R12) [[2]](diffhunk://#diff-5555b79aaee8a14d94af70b8465705692bc6456437c5097564e346d677ad3376R31-R37)
* [`src/Caliburn.Micro.Maui/Caliburn.Micro.Maui.csproj`](diffhunk://#diff-f0ca3f359c04f007369a684fa1ccf6cd4a306d84d09b0dbabfe0632ff45d5762R …

update nuget settings in project files

---

samples/features/Features.Avalonia/ViewModels/ShellViewModel.cs
samples/features/Features.CrossPlatform.Shared/ViewModels/ActionsViewModel.cs
samples/features/Features.CrossPlatform.Shared/ViewModels/Events/EventSourceViewModel.cs
samples/features/Features.CrossPlatform.Shared/ViewModels/NavigationTargetViewModel.cs
src/Caliburn.Micro.Avalonia/Caliburn.Micro.Avalonia.csproj
src/Caliburn.Micro.Core.Tests/ConductorWithCollectionOneActiveTests.cs
src/Caliburn.Micro.Core.Tests/ScreenExtentionTests.cs
src/Caliburn.Micro.Core/SimpleContainer.cs
src/Caliburn.Micro.Platform.Core/StringSplitter.cs
src/Caliburn.Micro.Platform/BindingScope.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/WindowConductor.cs
src/Caliburn.Micro.Platform/Platforms/netcore-avalonia/BootstrapperBase.cs
src/Caliburn.Micro.Platform/Platforms/netcore-avalonia/TriggerAction.cs
src/Caliburn.Micro.Platform/Platforms/netcore-avalonia/WindowConductor.cs

This pull request includes various changes across multiple files to improve code quality, fix issues, and add documentation. The most important changes include suppressing warnings, fixing field initialization, and adding documentation comments.
* [`samples/features/Features.Avalonia/ViewModels/ShellViewModel.cs`](diffhunk://#diff-7a99c1782fcb63eb5d908242be6e29af93f753f6a33917367eb13e821ea242d1R13-R17): Suppressed CS8618 warning for `_navigationService` not having a value in the constructor.
* [`samples/features/Features.CrossPlatform.Shared/ViewModels/ActionsViewModel.cs`](diffhunk://#diff-4626ad1aea99eb79abca253e10b41a04fe7b6e38609ae2b5cbecd9969c691c13L12-R12): Corrected field initialization for `_output`.
* [`samples/features/Features.CrossPlatform.Shared/ViewModels/Events/EventSourceVi …

Refactor ViewModel fields and add XML documentation

---

src/Caliburn.Micro.Platform/Platforms/uap/AttachedCollection.81.cs

This pull request refactors the code in `AttachedCollection.81.cs` to improve readability and maintainability by adopting a consistent coding style. The changes primarily involve reformatting code to follow standard C# conventions, such as placing braces on new lines and simplifying conditional logic.
* Updated the namespace and class definitions to place opening braces `{` on new lines, adhering to standard C# formatting conventions. [[1]](diffhunk://#diff-6a3ec20179c8d8304236c17f88811503ffd0e44d36a6a368d9c88af4d6c8c049L1-R2) [[2]](diffhunk://#diff-6a3ec20179c8d8304236c17f88811503ffd0e44d36a6a368d9c88af4d6c8c049L18-R86)
* Reformatted method definitions (`Attach`, `Detach`, `OnItemAdded`, `OnItemRemoved`, `OnVectorChanged`) to place braces `{` on new lines for consistency.
* Simplified …

missed if statement

---

src/Caliburn.Micro.Platform/Platforms/netcore-avalonia/BootstrapperBase.cs

protected override void OnSingleViewPlatformStartup(ISingleViewApplicationLifetime singleViewPlatform)
{
DisplaySingleViewFor<MainViewModel>(singleViewPlatform);
}

feat: support for avalonia of ISingleViewApplicationLifetime (Web Assembly)
