Caliburn-Micro/Caliburn.Micro

samples/Caliburn.Micro.KeyBinding/Caliburn.Micro.KeyBinding/KeyBindingBootstrapper.cs
samples/Caliburn.Micro.KeyBinding/Caliburn.Micro.KeyBinding/ShellView.xaml
samples/Caliburn.Micro.KeyBinding/Caliburn.Micro.KeyBinding/ShellViewModel.cs

I was looking at the Caliburn.Micro samples for keybinding and noticed that while it had code to parse a gesture with keys and modifiers, there was no example of how to use it. Since I needed this functionality, I added an extra Gesture trigger to use the converter to construct a KeyTrigger that has modifiers.
One drawback is that since the KeyTrigger class only supports one Key, it does not make full use of the MultiKeyGesture functionality.
If there is a better way to make use of the MultiKeyGesture/Binding code provided in this sample, please let me know so I can figure out how to use it that way. I'm no expert on the System.Windows.Input or System.Windows.Interactivity APIs at work here.

Added simple gesture trigger example

---

src/Caliburn.Micro.Extensions.WIN8/AppManifestHelper.cs

This PR fixes `SettingsWindowManager` for UAP.
UAP uses different namespace for `VisualElements` in `Package.appxmanifest`. As a result `SettingsWindowManager.ShowSettingsFlyout` throws `ArgumentNullException` from `AppManifestHelper.GetManifestVisualElementsAsync` method.
I fixed the namespace and changed `Square30x30Logo` to new `Square44x44Logo`.

Using updated AppxManifest.xml format for UAP

---

src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.Xamarin.Forms.csproj
src/packages/repositories.config

Line 103 caused build errors if Xamarin.Forms 1.3.1.6296 was not present.

Fixes references to Xamarin.Forms package

---

src/Caliburn.Micro.Platform/net40/WindowManager.cs

This is a fix for an edge case where code that is not under my control closes the Application.Current.MainWindow (without closing the actual application because it's native c++ in which WPF is hosted). This previously raises an exception when that closed window is used as Owner when creating a new Dialog.
Using PresentationSource.FromVisual as per http://stackoverflow.com/a/26355993/481635

Make sure MainWindow isn't disposed before using it as owner

---

src/Caliburn.Micro.Platform/NameTransformer.cs

This is a heavily used codepath. I ran tests, compiled regex is faster (excluding first hit).
The first hit is about 8 times slower, but still a very low number (7 milliseconds on my machine).

NameTransformer is faster with compiled Regex

---

src/Caliburn.Micro.Platform/ConventionManager.cs

Modified the directive for WP81 to include the WINDOWS_UWP directive, which now has access to the Pivot control in Windows UAP apps.

Pivot control & Windows UWP

---

src/Caliburn.Micro.Extensions.WIN8/AppManifestHelper.cs

You need to enter the value `transparent` as the background color in the app manifest to make your logos background transparent. If you do so, the settings service will throw a parse exception once you enter a settings flyout. This fix checks if you entered that value and returns a `Transparent` color object.

'transparent' value validation

---

src/Caliburn.Micro.Platform/ViewLocator.cs

I think it's a good idea to try to retrieve single instance when GetAllInstances returns empty collection.
See https://github.com/simpleinjector/SimpleInjector/issues/251#issuecomment-225718891

Fix dependency injection issue

---

src/Caliburn.Micro.Platform/xforms/NavigationPageAdapter.cs

This change allows the `NavigationPageAdapter` to also use a `ContentView` when navigating. I found Xamarin to be a bit too restrictive around it's usage of these for no real reason.
FWIW this allows the same top level view to be either composed as part of a tab/master detail or be navigated to using the navigation service without actually having to change the object type. I wasn't too sure whether this behavior should be baked into the `NavigationPageAdapter` or whether an additional extension point should be added allowing the user to intercept the view and modify it right before it is bound, but happy to make those changes as well if you think it would be worthwhile.

[WIP] Adapt ContentViews to ContentPages during navigation

---

src/Caliburn.Micro.Tests.NET45/RegExHelperTests.cs
src/Caliburn.Micro.Tests.NET45/StringSplitterTests.cs
src/Caliburn.Micro.Tests.NET45/ViewLocatorTests.cs

Fixed a few spelling errors in the unit tests that had extra characters and some off-casing. No functionality was changed.

Fixed spelling errors in test names

---

src/Caliburn.Micro.Platform/net40/WindowManager.cs
src/Caliburn.Micro.Platform/sl4/WindowManager.cs

As discussed in #462 the window title is taken from the window property instead of always using a binding.

Use explicit title for windows and pages

---

src/Caliburn.Micro/Conductor.cs
src/Caliburn.Micro/ConductorWithCollectionAllActive.cs
src/Caliburn.Micro/ConductorWithCollectionOneActive.cs
src/Caliburn.Micro/Screen.cs

When using a doc generator (such as Ghostdoc) alongside StyleCop, it would import the spelling mistake and Stylecop would keep flagging it up. This would always happen when overriding OnDeactivate.
A trivial thing but it somehow bothered me greatly enough to do this.

[Documentation] Fixed spelling of 'Inidicates' with 'Indicates'

---

src/Caliburn.Micro.Platform/xforms/NavigationPageAdapter.cs

This is a small tweak to the Xamarin.Forms NavigationPageAdapter to allow users to apply additional logic when a page is pushed or popped from the navigation stack.
As an example, I have a cross-cutting concern for network connectivity in my application. Users are able to navigate while offline, but I need a visual indicator on each page to show connectivity. Rather than have all pages in the application query the network status on activation, it would be ideal if the network status was provided to them externally as they navigated. With this PR I can subclass NavigationPageAdapter to provide status when pages are pushed/popped.

Update Xamarin.Forms NavigationPageAdapter

---

src/Caliburn.Micro.Platform/Platforms/Xamarin.Forms/FormsApplication.cs

The Exception occurs when the iOS app launches. It is due to `NavigationPage` being rendered before the root view has been set. Android applications are not affected since the root page check occurs in platform-specific code.
Exception details are:
> NavigationPage must have a root Page before being used. Either call PushAsync with a valid Page, or pass a Page to the constructor before usage. (System.InvalidOperationException)
at Xamarin.Forms.Platform.iOS.NavigationRenderer.ViewDidLoad () <0x10115fc60 + 0x0071c> in <bc5a3d4303744676b3b36f4254bb697d#fcf3a1c8209da1af9ec91eac76a1af7b>:0
at (wrapper managed-to-native) ObjCRuntime.Messaging:objc_msgSendSuper (intptr,intptr)
at UIKit.UIViewController.get_View () <0x100a62790 + 0x00073> in …

[WIP] Fix for InvalidOperationException when iOS app starts

---

nuget/start/content/net40/ShellView.xaml.cs.pp
nuget/start/content/net45/ShellView.xaml.cs.pp

This is a stab at [Issue 529](https://github.com/Caliburn-Micro/Caliburn.Micro/issues/529).
My attempt is inspired by the default VS itemtemplate for windows. 
- added partial class to .NET 4.0 package
- added partial class to .NET 4.5 package
I did not add a partial class to the Silverlight UserControl because I am unsure how those work..

partial ShellView-class added

---

samples/scenarios/Scenario.KeyBinding/Input/KeyTrigger.cs
samples/scenarios/Scenario.KeyBinding/ViewModels/ShellViewModel.cs
samples/scenarios/Scenario.KeyBinding/Views/ShellView.xaml

KeyTrigger class in KeyBinding sample could not match Alt-key combinations because the actual key code gets pushed into the SystemKey field.  Fixed KeyTrigger and added to sample to test it.

Allow KeyTrigger to match Alt+Key combinations

---

azure-pipeline.yml
samples/features/Features.UWP/Features.UWP.csproj
samples/setup/Setup.Forms/Setup.Forms.Droid/Setup.Forms.Droid.csproj
src/Caliburn.Micro.Core/BindableCollection.cs
src/Caliburn.Micro.Core/Caliburn.Micro.Core.csproj
src/Caliburn.Micro.Core/PropertyChangedBase.cs
src/Caliburn.Micro.Platform.Tests/Caliburn.Micro.Platform.Tests.csproj
src/Caliburn.Micro.Platform/ActionMessage.cs
src/Caliburn.Micro.Platform/Bind.cs
src/Caliburn.Micro.Platform/BindingScope.cs
src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj
src/Caliburn.Micro.Platform/ConventionManager.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/AssemblyInfo.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/AttachedCollection.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/Bootstrapper.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/INavigationService.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/NavigationExtensions.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/NavigationHelper.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/Parameter.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/WindowManager.cs
src/Directory.Build.targets
src/global.json

As #609 seems to be stuck at the moment I took the liberty to replicate the changes and include the review suggestions from @nigel-sampson.
I also renamed the folder containing the shared files from `net46` to `net46-netcore`.

Add .NET Core 3.0 target to Caliburn.Micro.Platform

---

src/Caliburn.Micro.Platform/Platforms/Xamarin.Forms/NavigationPageAdapter.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/WindowManager.cs
src/Caliburn.Micro.Platform/Platforms/net46/WindowManager.cs

There are two typos where a method suffix is "Aysnc" instead of "Async":
- The private method CanCloseAysnc of NavigationPageAdapter.
- The public method InitialiseAysnc of private class WindowConductor.

Rename methods with "Aysnc" to "Async"

---

src/Caliburn.Micro.Core/EventAggregator.cs

The HandlerExistsFor() method in EventAggregator uses the logical AND
operator & instead of the conditional logical AND operator &&.

Use short-circuit AND operator in EventAggregator

---

src/Caliburn.Micro.Core/Conductor.cs
src/Caliburn.Micro.Core/ConductorBase.cs
src/Caliburn.Micro.Core/ConductorWithCollectionAllActive.cs
src/Caliburn.Micro.Core/ConductorWithCollectionOneActive.cs
src/Caliburn.Micro.Core/DefaultCloseStrategy.cs
src/Caliburn.Micro.Core/EventAggregator.cs
src/Caliburn.Micro.Core/IActivate.cs
src/Caliburn.Micro.Core/ICloseStrategy.cs
src/Caliburn.Micro.Core/IConductor.cs
src/Caliburn.Micro.Core/IDeactivate.cs
src/Caliburn.Micro.Core/IEventAggregator.cs
src/Caliburn.Micro.Core/IGuardClose.cs
src/Caliburn.Micro.Core/Screen.cs
src/Caliburn.Micro.Core/ScreenExtensions.cs

This adds default CancellationTokens to many common methods that are likely to be called by the user of this library (I did not add it to the event like methods like OnInitalized).
This fixes #663 
Since for some mehtods there was already a overload without a CancellationToken I tried to be consistent inside a class. That means if the class already conatined such overloads for some methods I did add overloads without CancellationToken for the remaining ones in this class, otherwise I provided a default value for the existing declarations.

added default CancellationTokens to common methods (fixes #663)

---

src/Caliburn.Micro.Core/Caliburn.Micro.Core.csproj
src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj

Possible solution to #700
Tweaks for consistent strong-naming.
Also, reduced the number of targets required.

Strong-name all Assemblies

---

.github/CONTRIBUTING.md

Issue #648 did not state the exact error that occurred when opening the solution but if the SDK is missing (as described in https://github.com/novotnyllc/MSBuildSdkExtras/issues/190) the solution fails to load.
This is an obscure error message that is hard to search for within this repository. This modification adds a simple and prominent FAQ that explains the problem and how to fix it.

Add FAQ for obscure SDK missing error message

---

src/Caliburn.Micro.Platform.Tests/ParserTests.cs
src/Caliburn.Micro.Platform/Parser.cs

Fixes #521 
Changes the char.IsNumber to decimal.TryParse as the try parse will take the sign into account.

Fixes the parsing of negative numbers in action parameters #521

---

src/Caliburn.Micro.Platform/Platforms/Xamarin.Forms/ActionMessage.cs

When the OnAttached event was fired the Parameters had not yet been added to the parameters collection and was never made aware of the owning ActionMessage. A CollectionChanged EventHandler on the parameters collection is used to call MakeAwareOf.
Fixes #517

Parameter was not made aware of owner because of assignment order #517

---

src/Caliburn.Micro.Core.Tests/ScreenExtentionTests.cs
src/Caliburn.Micro.Core/AsyncEventHandler.cs
src/Caliburn.Micro.Core/AsyncEventHandlerExtensions.cs
src/Caliburn.Micro.Core/IDeactivate.cs
src/Caliburn.Micro.Core/Screen.cs
src/Caliburn.Micro.Core/ScreenExtensions.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/WindowConductor.cs

I would like some feed back on this, do you guys think it is a good idea to try and use AsyncEventHandlers? Have I missed something that would break current functionality?
I really dont see any other way to fix #618 as @nigel-sampson stated in the issue async and normal eventhandlers do not mix.

WIP Prosal on how to fix #618 by implementing AsyncEventHandlers

---

src/Caliburn.Micro.Core/DefaultCloseStrategy.cs

When the conductor cannot close, the default of the DefaultCloseStrategy should not close the conducted items.
This PR fixes this issue

Fix bug that causes children to close when parent cannot close

---

samples/features/Features.NetCore/Bootstrapper.cs
samples/features/Features.NetFive/Bootstrapper.cs
samples/features/Features.WPF/Bootstrapper.cs
src/Caliburn.Micro.Platform/Platforms/net46-netcore/Bootstrapper.cs
src/Caliburn.Micro.Platform/Platforms/net46/Bootstrapper.cs

Adds DisplayRootViewForAsync<T> to .net framework and .net core wpf projects.  This is related to issue #760

Add DisplayRootViewForAsync<T> for net 461 and dot net core

---

src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj

Remove Nuget package Microsoft.Windows.Compatibility which is not needed for .net 5 and .net 6 wpf apps.
Closes Bug #786

remove nuget packages that are not needed for .net 5 and 6

---

src/Caliburn.Micro.Core/Screen.cs

This is in relation to
https://github.com/Caliburn-Micro/Caliburn.Micro/issues/593. I agree with the issue but is a pretty big breaking change for us. This should allow the correct sequence of activation, activated callbacks.

Allow view to be notified

---

src/Caliburn.Micro.Core/SimpleContainer.cs
src/Caliburn.Micro.Platform/Bind.cs
src/Caliburn.Micro.Platform/Platforms/Maui/Windows/MauiPlatformProvider.cs
src/Caliburn.Micro.Platform/Platforms/uap/FrameAdapter.cs
src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs
src/Caliburn.Micro.Platform/XamlPlatformProvider.cs

Made several fields `readonly` based on Code QL suggestions (Caliburn-Micro#875). This ensures they are only assigned during declaration or inside constructors.
Affected files:
- src/Caliburn.Micro.Core/SimpleContainer.cs
- src/Caliburn.Micro.Platform/Bind.cs
- src/Caliburn.Micro.Platform/Platforms/Maui/Windows/MauiPlatformProvider.cs
- src/Caliburn.Micro.Platform/Platforms/uap/FrameAdapter.cs
- src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs
- src/Caliburn.Micro.Platform/XamlPlatformProvider.cs

Add `readonly` modifier to fields

---

samples/tutorals/WPF/Wpf.Tutorial/Caliburn.Micro.Tutorial.Wpf/Bootstrapper.cs

List of Changes:
1. The code line initializing a variable "c" with the instance of "SimpleContainer" has been altered. The updated code no longer assigns the instance to the variable "c", but simply gets the instance of "SimpleContainer" without storing it in any variable. This change suggests that the variable "c" was not being used elsewhere in the code, hence it was removed to improve code cleanliness and efficiency.

This change was made to enhance code cleanliness and efficiency in tutorial app

---

samples/features/Features.CrossPlatform.Shared/ViewModels/ActionsViewModel.cs
samples/features/Features.CrossPlatform.Shared/ViewModels/CoroutineViewModel.cs
samples/features/Features.CrossPlatform.Shared/ViewModels/NavigationSourceViewModel.cs
samples/features/Features.CrossPlatform.Shared/ViewModels/NavigationTargetViewModel.cs
samples/features/Features.NetFive/Views/ActionsView.xaml
samples/features/Features.NetFive/Views/CoroutineView.xaml
samples/features/Features.NetFive/Views/NavigationSourceView.xaml
samples/features/Features.NetFive/Views/NavigationTargetView.xaml
samples/features/Features.UWP/Views/ActionsView.xaml
samples/features/Features.UWP/Views/CoroutineView.xaml
samples/features/Features.UWP/Views/MenuView.xaml
samples/features/Features.UWP/Views/NavigationSourceView.xaml
samples/features/Features.UWP/Views/NavigationTargetView.xaml
samples/features/Features.WPF/Views/ActionsView.xaml
samples/features/Features.WPF/Views/CoroutineView.xaml
samples/features/Features.WPF/Views/NavigationSourceView.xaml
samples/features/Features.WPF/Views/NavigationTargetView.xaml

Renamed parameters in ActionsViewModel.cs methods for clarity. 
Removed unused usings and updated VisualStateResult in CoroutineViewModel.cs. 
Renamed private fields and properties in NavigationSourceViewModel.cs. 
Updated property names in NavigationTargetViewModel.cs. 
Renamed controls and updated bindings in ActionsView.xaml. 
Changed VisualState name in CoroutineView.xaml.
Renamed controls in NavigationSourceView.xaml and NavigationTargetView.xaml.
Closes #913

Refactor ViewModels and Views for naming consistency

---

src/Caliburn.Micro.Platform/ActionMessage.cs

Refactored ActionMessage class to improve readability and maintainability:
- Reformatted constructor, properties, methods, and delegates to include braces `{}` on new lines.
- Removed unnecessary comments.
- Removed unnecessary if statement
Closes #918

Refactor ActionMessage class for readability and remove if statement that is not needed for UWP

---

src/Caliburn.Micro.Platform/Platforms/Maui/ConventionManager.cs
src/Caliburn.Micro.Platform/Platforms/Xamarin.Forms/ConventionManager.cs

Reformatted several methods to use multi-line blocks for better readability. Changed `HorizontalOptions` and `VerticalOptions` of `ContentView` from `FillAndExpand` to `Fill`. Removed redundant empty lines and fixed spacing in property initialization
Closes #915

Refactor methods and update layout options

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dotnet.yml

Updated `codeql-analysis.yml` to use `global-json-file` for .NET setup.
In `dotnet.yml`, added `nuget_upload` env variable, switched to `global-json-file` for .NET setup, specified `java-version` 17, removed GitHub NuGet source step, added unit test step with coverage, and updated NuGet publishing to use `nuget_upload`. 
Added `dependabot.yml` for automated dependency updates.
Closes #932

Update CI/CD configs and add Dependabot support

---

.github/workflows/codeql-analysis.yml
.github/workflows/dotnet.yml
azure-pipeline.yml
samples/features/Features.NetFive/Features.DotNet.csproj
samples/setup/Setup.UWP/Setup.UWP.csproj
samples/setup/Setup.WPF.Core.VB/Bootstrapper.vb
samples/setup/Setup.WPF.Core.VB/Setup.WPF.Core.VB.vbproj
samples/setup/Setup.WPF.Core/Bootstrapper.cs
samples/setup/Setup.WPF.Core/Setup.WPF.Core.csproj
src/Caliburn.Micro.Core.Tests/EventAggregatorTests.cs
src/Caliburn.Micro.Core/EventAggregator.cs
src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj
src/global.json

This pull request includes updates to the `.NET` workflow and the `Caliburn.Micro.Platform` project file to support new .NET versions and improve the build and test processes. The most important changes include updating the .NET version, adding new target frameworks, and enhancing the workflow steps.
* Updated the .NET version from `8.0.x` to `9.0.x` in the `.github/workflows/dotnet.yml` file.
* Added a step to run unit tests with coverage collection in the `.github/workflows/dotnet.yml` file.
* Simplified the NuGet package push command by using a new environment variable in the `.github/workflows/dotnet.yml` file.
* Added `net9.0-android`, `net9.0-ios`, and `net9.0-windows` to the `TargetFrameworks` in the `Caliburn.Micro.Platform.csproj` file.
* Added conditional `ItemGroup`s for …

Add .net 9 to platform

---

src/Caliburn.Micro.Core/ContinueResultDecorator.cs
src/Caliburn.Micro.Core/OverrideCancelResultDecorator.cs
src/Caliburn.Micro.Core/RescueResultDecorator.cs
src/Caliburn.Micro.Core/ResultDecoratorBase.cs
src/Caliburn.Micro.Platform/Bind.cs
src/Caliburn.Micro.Platform/Platforms/Maui/HttpUtility.cs

Changed parameter name `innerResult` to `methodInnerResult` in `OnInnerResultCompleted` method across multiple files in the `Caliburn.Micro` namespace for consistency:
- `ContinueResultDecorator.cs`
- `OverrideCancelResultDecorator.cs`
- `RescueResultDecorator.cs`
- `ResultDecoratorBase.cs`
Removed unnecessary variable `keys` in `HttpUtility.cs` within the `Caliburn.Micro.Maui` namespace, directly iterating over `this.Keys` in the `foreach` loop to simplify the code.
Closes #940
Closes #939

Refactor parameter names and simplify iteration

---

src/Caliburn.Micro.Platform/MessageBinder.cs
src/Caliburn.Micro.Platform/Platforms/uap/FrameAdapter.cs

Updated MessageBinder.cs:
- Modified SpecialValues dictionary initialization for consistent formatting and alignment.
- Optimized custom converter checks using TryGetValue for better performance and readability.
- Adjusted conditional compilation blocks for enum type checks for improved readability and consistency across platforms.
Updated FrameAdapter.cs:
- Simplified ResumeStateAsync method by using TryGetValue for dictionary lookups, enhancing performance.
- Streamlined CurrentParameter assignment with TryGetValue for efficiency.

Optimize dictionary usage and improve code readability

---

src/Caliburn.Micro.Platform/MessageBinder.cs

Replaced the `if-else` statement with a ternary conditional operator for assigning `finalValues[i]`. This change makes the code more concise by combining the condition and assignment into a single line, improving readability and maintainability.

Refactor conditional assignment to use ternary operator

---

samples/features/Features.Avalonia/ViewModels/ShellViewModel.cs
samples/features/Features.Avalonia/Views/NavigationSourceView.axaml
samples/features/Features.Avalonia/Views/NavigationTargetView.axaml
samples/features/Features.Avalonia/Views/ShellView.axaml
src/Caliburn.Micro.Platform/Platforms/netcore-avalonia/NavigationFrame.cs

This pull request includes several changes to enhance navigation functionality and improve the user interface in the Avalonia application. The most important changes include the addition of a `GoBack` method, updates to navigation views, UI improvements, and enhancements to the `NavigationFrame` class.
Enhancements to navigation functionality:
* [`samples/features/Features.Avalonia/ViewModels/ShellViewModel.cs`](diffhunk://#diff-7a99c1782fcb63eb5d908242be6e29af93f753f6a33917367eb13e821ea242d1R45-R53): Added a new `GoBack` method to handle backward navigation.
* [`src/Caliburn.Micro.Platform/Platforms/netcore-avalonia/NavigationFrame.cs`](diffhunk://#diff-04bf70dd2df56367122b1463aa88e00816edebbf78feba1e7001e579944f6932L18-R20): Implemented navigation stack management and the `GoBackAsync` …

Update Avalonia UI features

---

src/Caliburn.Micro.Core/SimpleContainer.cs

Potential fix for [https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/82](https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/82)
To fix the issue, we will replace the `foreach` loop on line 184 with a LINQ `Where` clause applied to the `instances` sequence. This will explicitly filter the sequence before iterating over it, making the code more readable and reducing nesting depth. The filtering condition `EnablePropertyInjection && instance != null` will be moved to the `Where` method.
No new methods, imports, or definitions are required to implement this change, as LINQ is already imported (`using System.Linq`).

Potential fix for code scanning alert no. 82: Missed opportunity to use Where

---

src/Caliburn.Micro.Platform/Parser.cs

Potential fix for [https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/67](https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/67)
To fix the issue, the nested `if` statements should be combined into a single `if` statement using the `&&` operator. This simplifies the code and eliminates unnecessary nesting. The conditions should be enclosed in parentheses to ensure correct operator precedence.
The specific change involves combining the `if (withParameters != null)` and `if (closingParenthesisIndex - openingParenthesisIndex > 1)` statements into a single `if` statement. No additional imports, methods, or definitions are required.
---

Potential fix for code scanning alert no. 67: Nested 'if' statements can be combined

---

src/Caliburn.Micro.Platform/Platforms/Maui/Windows/MauiPlatformProvider.cs

Removed the assignment of the result from `dispatcher.RunAsync` to a variable. The discard operator `_` is now used to indicate that the result is not needed, streamlining the code.

Simplify async call by removing unused variable

---

src/Caliburn.Micro.Platform/Platforms/uap/AppManifestHelper.cs
src/Caliburn.Micro.Platform/Platforms/uap/FrameAdapter.cs

This pull request includes changes to improve code readability, simplify logic, and address potential memory management concerns in the `Caliburn.Micro.Platform` project. The most significant updates include refactoring the `ToColor` method for better clarity, reorganizing event handler initialization in `FrameAdapter`, and removing redundant code.
* Refactored the `ToColor` method in `AppManifestHelper.cs` to simplify logic for determining the start position and default alpha value. Introduced a boolean variable `isEightCharactersLong` for clarity and reduced redundant code.
* Reorganized event handler initialization in the `FrameAdapter` class. Added a new `AddEventHandlers` method to encapsulate the setup of navigation-related event handlers, improving code organization and addressing …

Refactor color parsing and improve FrameAdapter structure

---

src/Caliburn.Micro.Platform/Platforms/uap/AttachedCollection.81.cs

Potential fix for [https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/73](https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/73)
To fix the issue, the nested `if` statements on lines 68-70 should be combined into a single `if` statement. The conditions `item is IAttachedObject` and `((IAttachedObject)item).AssociatedObject != null` should be joined using the `&&` operator. Parentheses should be used around each condition to ensure proper operator precedence and maintain clarity. This change will simplify the code while preserving its functionality.
---

Potential fix for code scanning alert no. 73: Nested 'if' statements can be combined

---

src/Caliburn.Micro.Platform/Platforms/Xamarin.Forms/HttpUtility.cs

Potential fix for [https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/19](https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/19)
To fix the issue, the assignment to the variable `keys` on line 47 should be removed entirely. The `foreach` loop already accesses `this.Keys` directly, so the variable `keys` is unnecessary. This change will eliminate the redundant assignment and improve code clarity.
---

Potential fix for code scanning alert no. 19: Useless assignment to local variable

---

src/Caliburn.Micro.Platform/Platforms/net46-netcore/FrameAdapter.cs

Potential fix for [https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/1](https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/1)
To fix the issue, the explicit call to `GC.Collect()` on line 121 should be removed. This will allow the garbage collector to manage memory automatically without interference. If the application uses unmanaged resources, ensure they are properly disposed of using the `IDisposable` pattern and `try`/`finally` blocks. No additional changes are required in this specific method unless there is evidence of unmanaged resource usage elsewhere in the class.
---

Potential fix for code scanning alert no. 1: Call to GC.Collect()

---

src/Caliburn.Micro.Platform.Core/ExtensionMethods.cs
src/Caliburn.Micro.Platform.Core/StringSplitter.cs
src/Caliburn.Micro.Platform/Platforms/netcore-avalonia/NavigationFrame.cs
src/Caliburn.Micro.Platform/Platforms/uap/CaliburnApplication.cs

This pull request introduces several enhancements and refactorings across multiple files in the `Caliburn.Micro.Platform.Core` and `Caliburn.Micro.Platform` projects. The changes include the addition of a utility method, improvements to string manipulation logic, and updates to the `NavigationFrame` class to enhance functionality and documentation. Below are the most important changes grouped by theme.
* Added a new extension method `IsNullOrEmpty` for `StringBuilder` in `src/Caliburn.Micro.Platform.Core/ExtensionMethods.cs`. This simplifies checks for empty or null `StringBuilder` instances.
* Updated the `Split` method in `src/Caliburn.Micro.Platform.Core/StringSplitter.cs` to ensure that the separator is only considered when not inside square brackets, improving parsing accuracy. Also …

Added missing xml comments to NaviagationFrame and CaliburnApplication

---

src/Caliburn.Micro.Platform.Core/ExtensionMethods.cs
src/Caliburn.Micro.Platform/Platforms/uap/CaliburnApplication.cs

This pull request includes minor documentation improvements and the addition of new utility methods. The changes enhance code readability and functionality by fixing typos, improving XML documentation, and introducing a new extension method for `StringBuilder`.
* Fixed a typo in the XML documentation for `GetAssemblyName` in `ExtensionMethods.cs` ("Get's" corrected to "Gets").
* Updated the XML documentation for `GetValueOrDefault` in `ExtensionMethods.cs` to clarify the behavior when a key does not exist.
* Added a new extension method `IsNullOrEmpty` for `StringBuilder` in `ExtensionMethods.cs`, which checks whether a `StringBuilder` is null or has a length of zero.
* Added XML documentation for the `CreateWindow` and `InitializeWindow` methods in `CaliburnApplication.cs` to describe …

Add missing xml comments

---

src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs

Potential fix for [https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/253](https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/253)
To fix the issue, the nested `if` statements should be combined into a single `if` statement using the `&&` operator. This will reduce unnecessary nesting and make the code more concise. Specifically, the condition `if (String.Compare(valuePart.Trim(), key, StringComparison.OrdinalIgnoreCase) == 0)` and the inner condition `if (_enumValues.TryGetValue(key.Trim(), out partValue))` should be combined into a single `if` statement.
---

Potential fix for code scanning alert no. 253: Nested 'if' statements can be combined

---

src/Caliburn.Micro.Platform/Platforms/Xamarin.Forms/AttachedCollection.cs

Potential fix for [https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/71](https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/71)
To fix the issue, the nested `if` statements on line 58 and 59 should be combined into a single `if` statement using the `&&` operator. This will simplify the code and eliminate unnecessary nesting. The conditions should be enclosed in parentheses to ensure correct operator precedence.
The specific change involves replacing:
```cs
if (item is IAttachedObject) {
if (((IAttachedObject) item).AssociatedObject != null)
((IAttachedObject) item).Detach();
}
```
with:
```cs
if (item is IAttachedObject && ((IAttachedObject) item).AssociatedObject != null) {
((IAttachedObject) item).Detach();
}
```
No additional methods, imports, …

Potential fix for code scanning alert no. 71: Nested 'if' statements can be combined

---

src/Caliburn.Micro.Platform/Platforms/Maui/AttachedCollection.cs
src/Caliburn.Micro.Platform/Platforms/Xamarin.Forms/AttachedCollection.cs

This pull request introduces code style improvements and logic simplifications in the `AttachedCollection` classes for both the Maui and Xamarin.Forms platforms. The changes enhance readability and maintain consistency across the codebase.
* Updated method formatting in `src/Caliburn.Micro.Platform/Platforms/Maui/AttachedCollection.cs` to use consistent brace placement and simplify conditional logic in methods like `Detach`, `OnItemAdded`, `OnItemRemoved`, and `OnCollectionChanged`. [[1]](diffhunk://#diff-602ee3456c9b305181016dbd4a6f1248e739c02ab1e076e9abf0cbf943581823L30-R50) [[2]](diffhunk://#diff-602ee3456c9b305181016dbd4a6f1248e739c02ab1e076e9abf0cbf943581823L57-R63) [[3]](diffhunk://#diff-602ee3456c9b305181016dbd4a6f1248e739c02ab1e076e9abf0cbf943581823L68-R73)
* Applied the same …

Refactor AttachedCollection for readability and clarity

---

src/Caliburn.Micro.Avalonia/version.json
src/Caliburn.Micro.Maui/version.json
version.json

This pull request updates versioning information across the project, preparing for a stable 5.0 release and introducing version tracking for new components.
Versioning updates:
* Updated the root `version.json` to set the version from `"5.0-beta"` to the stable `"5.0"`, indicating readiness for a public release.
New version tracking for components:
* Added a new `version.json` to `src/Caliburn.Micro.Avalonia`, establishing independent versioning for this component and setting its version to `"5.0-beta"`.
* Added a new `version.json` to `src/Caliburn.Micro.Maui`, establishing independent versioning for this component and setting its version to `"5.0-beta"`.

1001 allow avalonia and maui to have different versions

---

src/Caliburn.Micro.Core.Tests/EventAggregatorExtensionsTests.cs

Implemented tests in `EventAggregatorExtensionsTests` to verify the correct behavior of the `EventAggregator` when subscribing and publishing messages across different threads. The tests ensure that the appropriate marshaller is invoked for UI thread subscriptions and confirm that messages are published correctly on both current and background threads. Additionally, a test was added to validate that all subscribed targets handle the published message on the current thread.
Issue #993

Add unit tests for EventAggregator thread behavior

---

samples/features/Features.Avalonia/Features.Avalonia.csproj
src/Caliburn.Micro.Avalonia.Tests/Caliburn.Micro.Avalonia.Tests.csproj
src/Caliburn.Micro.Avalonia/Caliburn.Micro.Avalonia.csproj

Updated project files for `Features.Avalonia`, `Caliburn.Micro.Avalonia.Tests`, and `Caliburn.Micro.Avalonia` to reference newer versions of Avalonia packages. Changed versions for `Avalonia`, `Avalonia.Desktop`, `Avalonia.Markup.Xaml.Loader`, `Avalonia.Themes.FLuent`, and `Avalonia.Diagnostics` from `11.2.x` to `11.3.5`. Added new package references for `Xaml.Behaviors.Avalonia` and `Xaml.Behaviors.Interactivity` at version `11.3.2` to leverage new features and improvements.

Update Avalonia packages to version 11.3.5

---

src/Caliburn.Micro.Avalonia/Caliburn.Micro.Avalonia.csproj

This pull request updates how project references are handled in the `Caliburn.Micro.Avalonia.csproj` file to improve compatibility and asset management for the referenced projects. The main changes involve specifying additional properties for project references and controlling which assets are included or excluded.
Project reference configuration improvements:
* Added an explicit `ItemGroup` for `Caliburn.Micro.Platform.Core` and `Caliburn.Micro.Core` project references, specifying `TargetFramework=netstandard2.0`, controlling asset inclusion/exclusion, and setting `ReferenceOutputAssembly` to true for both. (`src/Caliburn.Micro.Avalonia/Caliburn.Micro.Avalonia.csproj`, [src/Caliburn.Micro.Avalonia/Caliburn.Micro.Avalonia.csprojL32-R43](diffhunk://#diff-e3fbfc36d57f1c4655bfae32dfcc61544655 …

update Avalonia ui csproj for nuget
